### ISSUE TITLE
Minified library is not up to date

### ISSUE THREAD

**Issue by JonGarbayo** [tonai/jquery-contenttoggle#1]
Hi guy.

I think you forgot to update the minified version of your library ;)
When using it, with `independent` set as `false` (by default and as explicit parameter), the accordions don't work! Maybe there are other bugs, but I didn't tested more.

Thanks for reading!

**Comment by tonai** [comment]
Hi @JonGarbayo,
Thank you for your report.
Il will check this immediatly.

**Comment by tonai** [comment]
I have created a new v0.3.1 release with that correction.
Regards,
